version: "3"

services:
  postgresql:
    image: postgres
    restart: always
    container_name: postgres_test
    environment:
      POSTGRES_DB: toodle
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - test_env
    expose:
      - 5433
  backend:
    image: 626ksb/toodle_server
    restart: always
    container_name: backend
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: test
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/toodle
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    networks:
      - test_env

networks:
  test_env:
    driver: bridge