version: "3"

services:
  postgresql:
    image: postgres
    restart: always
    container_name: postgres_local
    environment:
      POSTGRES_DB: toodle
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
#    networks:
#      - test_env
    expose:
      - 5433
  redis:
    image: redis
    restart: always
    container_name: redis_local
    ports:
      - "6379:6379"
#  backend:
#    image: 626ksb/toodle_server
#    restart: always
#    container_name: backend
#    build: .
#    environment:
#      SPRING_PROFILES_ACTIVE: test
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/toodle
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgresql
#    networks:
#      - test_env
#  frontend:
#    image: 626ksb/toodle_frontend
#    restart: always
#    container_name: frontend
#    ports:
#      - "8300:80"
#  registry-login:
#    image: docker:stable
#    entrypoint: "/bin/sh"
#    command: "-c 'docker login -u {DOCKER_USERNAME} -p my-password {DOCKER_PASSWORD}'"

#networks:
#  test_env:
#    driver: bridge